// export { brightcove } from './brightcove.js';
export { dailymotion } from './dailymotion.js';
export { facebook } from './facebook.js';
export { file } from './file.js';
export { jwplayer } from './jwplayer.js';
export { soundcloud } from './soundcloud.js';
export { streamable } from './streamable.js';
export { twitch } from './twitch.js';
export { vidyard } from './vidyard.js';
export { vimeo } from './vimeo.js';
export { wistia } from './wistia.js';
export { youtube } from './youtube.js';
